### ISSUE TITLE
#feature private game with our Own words/language

### ISSUE THREAD

**Issue by G33kNoob** [codicocodes/speedtyper.dev#123]
hello, im very happy with the rust language available
but i want to learning type other language maybe golang/ruby, can you add feature to customize our own words ? maybe just add raw gist/github code

**Comment by codicocodes** [comment]
Thank you for the feedback. I'm not looking to add more languages right now. I am working on a version 2, which will have more languages available and new challenges with improved formatting.

In the future I would be open to allowing users to add their own projects by integrating with GitHub and syncing a selected project, but I'm not open to contributions on it right now since version2 needs to be completed first.
